In [2]:
import numpy as np
a=10
print(a,type(a))
ndo=np.array(a)
print(ndo,type(ndo))
print("Dimension:",ndo.ndim)
print("Data type:",ndo.dtype)
print("Shape of ndarray:",ndo.shape)
print("Size of ndarray:",ndo.size)

10 <class 'int'>
10 <class 'numpy.ndarray'>
Dimension: 0
Data type: int32
Shape of ndarray: ()
Size of ndarray: 1


In [3]:
import numpy as np
b=10.2
print(b,type(b))
ndo=np.array(b)
print(ndo,type(ndo))
print("Dimension:",ndo.ndim)
print("Data type:",ndo.dtype)
print("Shape of ndarray:",ndo.shape)
print("Size of ndarray:",ndo.size)

10.2 <class 'float'>
10.2 <class 'numpy.ndarray'>
Dimension: 0
Data type: float64
Shape of ndarray: ()
Size of ndarray: 1


In [4]:
import numpy as np
c=True
print(c,type(c))
ndo=np.array(c)
print(ndo,type(ndo))
print("Dimension:",ndo.ndim)
print("Data type:",ndo.dtype)
print("Shape of ndarray:",ndo.shape)
print("Size of ndarray:",ndo.size)

True <class 'bool'>
True <class 'numpy.ndarray'>
Dimension: 0
Data type: bool
Shape of ndarray: ()
Size of ndarray: 1


In [5]:
import numpy as np
d=10+2j
print(d,type(d))
ndo=np.array(d)
print(ndo,type(ndo))
print("Dimension:",ndo.ndim)
print("Data type:",ndo.dtype)
print("Shape of ndarray:",ndo.shape)
print("Size of ndarray:",ndo.size)

(10+2j) <class 'complex'>
(10+2j) <class 'numpy.ndarray'>
Dimension: 0
Data type: complex128
Shape of ndarray: ()
Size of ndarray: 1


In [7]:
import numpy as np
e='python'
print(e,type(e))
ndo=np.array(e)
print(ndo,type(ndo))
print("Dimension:",ndo.ndim)
print("Data type:",ndo.dtype)
print("Shape of ndarray:",ndo.shape)
print("Size of ndarray:",ndo.size)

python <class 'str'>
python <class 'numpy.ndarray'>
Dimension: 0
Data type: <U6
Shape of ndarray: ()
Size of ndarray: 1


In [8]:
import numpy as np
f=range(10)
print(f,type(f))
ndo=np.array(f)
print(ndo,type(ndo))
print("Dimension:",ndo.ndim)
print("Data type:",ndo.dtype)
print("Shape of ndarray:",ndo.shape)
print("Size of ndarray:",ndo.size)

range(0, 10) <class 'range'>
[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
Dimension: 1
Data type: int32
Shape of ndarray: (10,)
Size of ndarray: 10


In [9]:
import numpy as np
g=[10,20.5,"Von Rossum",True,2+3j]
print(g,type(g))
ndo=np.array(g)
print(ndo,type(ndo))
print("Dimension:",ndo.ndim)
print("Data type:",ndo.dtype)
print("Shape of ndarray:",ndo.shape)
print("Size of ndarray:",ndo.size)

[10, 20.5, 'Von Rossum', True, (2+3j)] <class 'list'>
['10' '20.5' 'Von Rossum' 'True' '(2+3j)'] <class 'numpy.ndarray'>
Dimension: 1
Data type: <U64
Shape of ndarray: (5,)
Size of ndarray: 5


In [10]:
h=[[10,20,30],[40,50,60],[70,80,90]]
print(h)
ndo=np.array(h)
print(ndo)

[[10, 20, 30], [40, 50, 60], [70, 80, 90]]
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [14]:
lst1=[1,2,3]
lst2=[4,5,6]
lst3=lst1+lst2
print(lst3)
nd1=np.array(lst1)
nd2=np.array(lst2)
print(nd1+nd2)
print(nd1*nd2)
print(np.add(lst1,lst2))
print(np.multiply(lst1,lst2))

[1, 2, 3, 4, 5, 6]
[5 7 9]
[ 4 10 18]
[5 7 9]
[ 4 10 18]


In [16]:
i=[1,2,3,4,5,6,7,8,9]
print(i)
ndo=np.array(i)
print(ndo)
print("Dimension:",ndo.ndim)
print("Data type:",ndo.dtype)
print("Shape:",ndo.shape)
print("Size:",ndo.size)
ndo=ndo.reshape(3,3)
print(ndo)
print("Dimension:",ndo.ndim)
print("Data type:",ndo.dtype)
print("Shape:",ndo.shape)
print("Size:",ndo.size)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1 2 3 4 5 6 7 8 9]
Dimension: 1
Data type: int32
Shape: (9,)
Size: 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimension: 2
Data type: int32
Shape: (3, 3)
Size: 9


In [18]:
j=range(0,4)
print(j)
ndo=np.array(j)
print(ndo)
print("Dimension:",ndo.ndim)
print("Data type:",ndo.dtype)
print("Shape:",ndo.shape)
print("Size:",ndo.size)
ndo=ndo.reshape(2,2)
print(ndo)
print("Dimension:",ndo.ndim)
print("Data type:",ndo.dtype)
print("Shape:",ndo.shape)
print("Size:",ndo.size)

range(0, 4)
[0 1 2 3]
Dimension: 1
Data type: int32
Shape: (4,)
Size: 4
[[0 1]
 [2 3]]
Dimension: 2
Data type: int32
Shape: (2, 2)
Size: 4
